### ISSUE TITLE
Range1 -> UnitRange

### ISSUE THREAD

**Issue by mvogelsb** [jverzani/PySide.jl#12]
Hi,

could you please change Range1 to UnitRange. I get the following error loading PySide:

julia> using PySide
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at ./deprecated.jl:63
 in require at deprecated.jl:648
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:264
 in require at ./loading.jl:203
while loading /home/mark/.julia/v0.4/PySide/src/PySide.jl, in expression starting on line 1
WARNING: could not import Base.help into PyCall
INFO: Recompiling stale cache file /home/mark/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Recompiling stale cache file /home/mark/.julia/lib/v0.4/Mustache.ji for module Mustache.
INFO: Recompiling stale cache file /home/mark/.julia/lib/v0.4/Requires.ji for module Requires.

WARNING: deprecated syntax "{a=>b, ...}" at /home/mark/.julia/v0.4/PySide/src/qtutils.jl:51.
Use "Dict{Any,Any}(a=>b, ...)" instead.
ERROR: LoadError: LoadError: UndefVarError: Range1 not defined
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:264
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:264
 in require at ./loading.jl:203
while loading /home/mark/.julia/v0.4/PySide/src/qtextras.jl, in expression starting on line 244
while loading /home/mark/.julia/v0.4/PySide/src/PySide.jl, in expression starting on line 30

Thanks!
Mark

**Comment by jverzani** [comment]
Thanks, should be fixed now. You can try with `Pkg.checkout("PySide")`.
